
GET http://localhost:8080/

### update handler
PATCH http://localhost:8081/
Content-Type: application/json

{
    "age":10,
    "skills": ["Rust", "Java"]
}

### url shortener
POST http://localhost:9876/
Content-Type: application/json

{
    "url": "https://google.com"
}

### get shortened url
GET http://127.0.0.1:9876/VUSvvU
